api:
  dashboard: true
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/configs"
    watch: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections: # <- just redirect to SSL
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"

# https://doc.traefik.io/traefik/reference/install-configuration/tls/certificate-resolvers/acme/
certificatesResolvers:
  http:
    acme:
      email: <your_email_here>
      storage: acme/http-acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: http
  dns:
    # https://doc.traefik.io/traefik/https/acme/
    acme:
      email: <your_email_here>
      storage: acme/dns-acme.json
      dnsChallenge:
        provider: <your_dns_provider>
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

serversTransport:
    insecureSkipVerify: true

accessLog:
  filePath: "/logs/access.log"
  fields:
    headers:
      names:
        User-Agent: keep
